name: useful_recorder
description: A new Flutter project.

version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any

  # 状态管理
  provider: any

  # 应用参数 & 应用数据
  shared_preferences: any
  sqflite: any

  # 表现力
  animations: any
  font_awesome_flutter: any
  flutter_material_pickers: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
